/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutobahnTab: typeof import('./src/components/searchTabs/AutobahnTab.vue')['default']
    LeafletMap: typeof import('./src/components/LeafletMap.vue')['default']
    MultiSelect: typeof import('./src/components/MultiSelect.vue')['default']
    RoadItemTooltip: typeof import('./src/components/tooltips/RoadItemTooltip.vue')['default']
    SearchButton: typeof import('./src/components/SearchButton.vue')['default']
    SearchDialog: typeof import('./src/components/SearchDialog.vue')['default']
  }
}
