/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbfallNaviSearch: typeof import('./src/components/searchTabs/AbfallNaviSearch.vue')['default']
    AbfallNaviSearchTab: typeof import('./src/components/searchTabs/AbfallNaviSearchTab.vue')['default']
    LeafletMap: typeof import('./src/components/LeafletMap.vue')['default']
    MultiSelect: typeof import('./src/components/MultiSelect.vue')['default']
    SearchDialog: typeof import('./src/components/SearchDialog.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
  }
}
