/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutobahnSearch: typeof import('./src/components/search/AutobahnSearch.vue')['default']
    LeafletMap: typeof import('./src/components/LeafletMap.vue')['default']
    MultiSelect: typeof import('./src/components/MultiSelect.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SearchButton: typeof import('./src/components/SearchButton.vue')['default']
  }
}
